using Microsoft.CodeAnalysis.CSharp;
using Shouldly;

namespace RoslynLens.Tests;

public class GeneratedCodeTests
{
    [Theory]
    [InlineData("/repo/obj/Debug/net10.0/App.GlobalUsings.g.cs")]
    [InlineData("/repo/src/bin/Release/Foo.cs")]
    [InlineData(@"C:\repo\obj\Debug\App.AssemblyInfo.cs")]
    [InlineData("/repo/src/Foo.generated.cs")]
    [InlineData("/repo/src/Form1.Designer.cs")]
    [InlineData("/repo/src/RegexHelper.g.cs")]
    public void IsGeneratedPath_ReturnsTrue_ForGeneratedPaths(string path) =>
        GeneratedCode.IsGeneratedPath(path).ShouldBeTrue();

    [Theory]
    [InlineData("/repo/src/Service.cs")]
    [InlineData("/repo/src/AssemblyInfo.cs")] // hand-written, not under obj/
    [InlineData("/repo/src/Robot.cs")] // contains "obj" substring but not a directory
    [InlineData(null)]
    [InlineData("")]
    public void IsGeneratedPath_ReturnsFalse_ForRealSource(string? path) =>
        GeneratedCode.IsGeneratedPath(path).ShouldBeFalse();

    [Fact]
    public void HasAutoGeneratedHeader_ReturnsTrue_WhenMarkerPresent()
    {
        var root = CSharpSyntaxTree.ParseText("""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            // </auto-generated>
            //------------------------------------------------------------------------------
            namespace A { public class Generated { } }
            """).GetRoot(TestContext.Current.CancellationToken);

        GeneratedCode.HasAutoGeneratedHeader(root).ShouldBeTrue();
    }

    [Fact]
    public void HasAutoGeneratedHeader_ReturnsFalse_ForHandWrittenCode()
    {
        var root = CSharpSyntaxTree.ParseText("""
            // A normal copyright header.
            namespace A { public class Service { } }
            """).GetRoot(TestContext.Current.CancellationToken);

        GeneratedCode.HasAutoGeneratedHeader(root).ShouldBeFalse();
    }
}
