using Microsoft.CodeAnalysis;

namespace RoslynLens;

/// <summary>
/// Generic detection of compiler-/tool-generated source so analysis tools can skip it.
/// Mirrors Roslyn's own heuristics: build-output directories, well-known generated
/// file-name suffixes, and the <c>&lt;auto-generated&gt;</c> header marker.
/// Intentionally framework-agnostic — no project- or domain-specific conventions.
/// </summary>
internal static class GeneratedCode
{
    private static readonly string[] GeneratedSuffixes =
    [
        ".g.cs", ".g.i.cs", ".generated.cs", ".designer.cs",
        ".assemblyattributes.cs", ".assemblyinfo.cs", ".globalusings.g.cs"
    ];

    /// <summary>
    /// True when the file path points at generated code: anything under an
    /// <c>obj/</c> or <c>bin/</c> build directory, or a known generated suffix.
    /// </summary>
    internal static bool IsGeneratedPath(string? filePath)
    {
        if (string.IsNullOrEmpty(filePath)) return false;

        var path = filePath.Replace('\\', '/');

        if (path.Contains("/obj/", StringComparison.OrdinalIgnoreCase) ||
            path.Contains("/bin/", StringComparison.OrdinalIgnoreCase))
            return true;

        var name = path[(path.LastIndexOf('/') + 1)..];
        return GeneratedSuffixes.Any(s => name.EndsWith(s, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// True when the syntax tree opens with an <c>&lt;auto-generated&gt;</c> header comment,
    /// the canonical marker emitted by source generators and designers.
    /// </summary>
    internal static bool HasAutoGeneratedHeader(SyntaxNode root)
    {
        var firstToken = root.GetFirstToken(includeZeroWidth: true);
        foreach (var trivia in firstToken.LeadingTrivia)
        {
            if (trivia.ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }
}
